CREATE TABLE faculty (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	num int8 NOT NULL,
    name varchar(64) NOT NULL,
    CONSTRAINT faculty_pkey PRIMARY KEY (id),
	CONSTRAINT faculty_num_uniq UNIQUE (num),
	CONSTRAINT faculty_name_uniq UNIQUE (name)
);

CREATE TABLE course (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	num int8 NOT NULL,
    name varchar(64) NOT NULL,
    faculty_id int8 NOT NULL,
    CONSTRAINT course_pkey PRIMARY KEY (id),
	CONSTRAINT course_num_uniq UNIQUE (num),
	CONSTRAINT course_name_uniq UNIQUE (name),
	CONSTRAINT course_faculty_uniq UNIQUE (num, faculty_id)
);

alter table course drop column name;

CREATE TABLE groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	num int8 NOT NULL,
    name varchar(64) NOT NULL,
    course_id int8 NOT NULL,
    CONSTRAINT group_pkey PRIMARY KEY (id),
	CONSTRAINT group_num_uniq UNIQUE (num),
	CONSTRAINT group_name_uniq UNIQUE (name),
	CONSTRAINT group_course_uniq UNIQUE (num, course_id)
);

alter table groups add column commercial boolean default false;

alter table groups drop column name;

--CREATE INDEX group_name ON groups USING btree (name);

CREATE TABLE student (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    first_name varchar(64) NOT NULL,
    last_name varchar(64) NOT NULL,
    middle_name varchar(64),
    date_of_birth date not null,
    inn int8 NOT NULL,
    groups_id int8 NOT NULL,
    CONSTRAINT student_pkey PRIMARY KEY (id),
	CONSTRAINT student_inn_uniq UNIQUE (inn)
);

--CREATE TYPE stipend_type AS ENUM ('normal', 'high', 'extra');

--CREATE TABLE stipend_type (
--	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
--    type varchar(64) NOT NULL,
--    amount numeric NOT NULL,
--    CONSTRAINT stipend_type_pkey PRIMARY KEY (id),
--	CONSTRAINT stipend_type_type_uniq UNIQUE (type),
--);

CREATE TABLE stipend (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	student_id int8 NOT NULL,
    base_amount numeric NOT NULL,
    coeff1 double precision default 1,
    coeff2 double precision default 1,
    dotation numeric default 0,
    amount numeric GENERATED ALWAYS AS (base_amount * coeff1 * coeff2 + dotation) stored,
    CONSTRAINT stipend_pkey PRIMARY KEY (id),
	CONSTRAINT stipend_student_id_uniq UNIQUE (student_id)
);

insert into faculty (num, name) values 
(51, 'ПИНЖ'),
(52, 'ФИИТ'),
(53, 'МЕХТЕХ');

insert into course (faculty_id, num) values 
(1, 11), (1, 12), (1, 13), (1, 14), (1, 15),
(2, 21), (2, 22), (2, 23), (2, 24), (2, 25),
(3, 31), (3, 32), (3, 33), (3, 34), (3, 35);

select * from course;

insert into groups (course_id, num, commercial) values 
(7, 111, false), (7, 112, false), (7, 113, true), 
(8, 121, false), (8, 122, false), (8, 123, true), 
(9, 131, false), (9, 132, false), (9, 133, true), 
(10, 141, false), (10, 142, false), (10, 143, true), 
(11, 151, false), (11, 152, false), (11, 153, true),
(12, 211, false), (12, 212, false), (12, 213, true), 
(13, 221, false), (13, 222, false), (13, 223, true), 
(14, 231, false), (14, 232, false), (14, 233, true), 
(15, 241, false), (15, 242, false), (15, 243, true), 
(16, 251, false), (16, 252, false), (16, 253, true), 
(17, 311, false), (17, 312, false), (17, 313, true), 
(18, 321, false), (18, 322, false), (18, 323, true), 
(19, 331, false), (19, 332, false), (19, 333, true), 
(20, 341, false), (20, 342, false), (20, 343, true), 
(21, 351, false), (21, 352, false), (21, 353, true);

select 
	f.id as faculty_id, 
	f.num as faculty_num, 
	f.name as faculty_name, 
	c.id as course_id, 
	c.num as course_num, 
	g.id as group_id, 
	g.num as group_num, 
	g.commercial 
from groups g
join course c on g.course_id = c.id
join faculty f on f.id = c.faculty_id
order by g.num
--limit 5

insert into student (groups_id, first_name, last_name, middle_name, date_of_birth, inn) values 
(1, 'Петр', 'Петров', 'Петрович', '2006-01-01', 525677889911),
(1, 'Иван', 'Иванов', 'Иванович', '2006-02-02', 525677889912),
(1, 'Никита', 'Никитин', 'Олегович', '2006-03-03', 525677889913),
(1, 'Марина', 'Маринина', 'Ивановна', '2006-03-04', 525677889914),
(1, 'Жанна', 'Сергеева', 'Алексеевна', '2006-01-01', 525677889915),
--
(2, 'Кирилл', 'Сергеев', 'Кириллович', '2006-11-05', 525677889916),
(2, 'Федя', 'Колбаскин', 'Потапович', '2006-10-10', 525677889917),
(2, 'Ольга', 'Петрова', 'Петровна', '2006-05-06', 525677889918),
(2, 'Валя', 'Изенштейн', 'Патрикеевна', '2006-12-03', 525677889919),
(2, 'Дмитрий', 'Оз', 'Осипович', '2006-06-07', 525677889920),
--
(3, 'Остап', 'Остапов', 'Изяславович', '2006-02-22', 525677889921),
(3, 'Гена', 'Офиногенов', 'Герасимович', '2006-07-30', 525677889923),
(3, 'Лена', 'Копытова', 'Валерьевна', '2006-08-09', 525677889924),
(3, 'Петр', 'Обломов', 'Иванович', '2006-01-16', 525677889925),
(3, 'Зина', 'Турбина', 'Леопольдовна', '2006-09-01', 525677889926),
--
(4, 'Аскольд', 'Распашный', 'Тигранович', '2005-01-01', 525677889927),
(4, 'Петр', 'Первый', 'Алексеевич', '2005-05-05', 525677889928),
(4, 'Данила', 'Мазила', 'Кириллович', '2005-12-11', 525677889929),
(4, 'Камила', 'Забила', 'Абдулкадеровна', '2005-07-02', 525677889930),
(4, 'Валентин', 'Амуров', 'Гавриилович', '2005-04-09', 525677889931),
--
(5, 'Хасан', 'Аскеров', 'Саидович', '2005-01-22', 525677889932),
(5, 'Ашот', 'Нетот', 'Раисович', '2005-11-11', 525677889933),
(5, 'Даша', 'Неваляшкина', 'Сергеевна', '2006-12-12', 525677889934),
(5, 'Элла', 'Накипелло', 'Назимовна', '2005-09-09', 525677889935),
(5, 'Каштан', 'Баклажан', 'Рамбутанович', '2005-06-26', 525677889936),
--
(6, 'Джон', 'Смит', '', '2005-02-23', 525677889937),
(6, 'Генрих', 'Штойц', 'Азимутович', '2005-08-06', 525677889938),
(6, 'Арам', 'Бабаян', 'Арамович', '2005-05-01', 525677889939),
(6, 'Ксюша', 'Изплюша', 'Ксилофоновна', '2005-02-11', 525677889940),
(6, 'Анна', 'Одинцова', 'Алексеевна', '2005-10-21', 525677889941)

select 
	s.id,
	first_name,
	middle_name,
	last_name,
	date_of_birth,
	inn,
    g.id as group_id,
	g.num as group_num,
	g.commercial,
	c.id as course_id,
	c.num as course_num,
	f.id as faculty_id,
	f.num as faculty_num, 
	f.name as faculty_name
from student s
join groups g on g.id = s.groups_id
join course c on c.id = g.course_id
join faculty f on f.id = c.faculty_id


select 
	s.id as student_id,
	s.first_name,
	s.middle_name,
	s.last_name,
	s.date_of_birth,
	s.inn,
    g.id as group_id,
	g.num as group_num,
	g.commercial,
	c.id as course_id,
	c.num as course_num,
	f.id as faculty_id,
	f.num as faculty_num, 
	f.name as faculty_name
from groups g
right join student s on g.id = s.groups_id
join course c on c.id = g.course_id
join faculty f on f.id = c.faculty_id

select count(*) 
from student s 
join groups g on g.id = s.groups_id
join course c on c.id = g.course_id
join faculty f on f.id = c.faculty_id
where f.name = 'ПИНЖ'

select 
	f.name,
	count(*) 
from student s 
join groups g on g.id = s.groups_id
join course c on c.id = g.course_id
join faculty f on f.id = c.faculty_id
group by f.name

select 
	g.num,
	count(*) 
from student s 
join groups g on g.id = s.groups_id
group by g.id

select 
	g.num as group_num,
	extract(month from s.date_of_birth) as month,
	count(*) 
from student s 
join groups g on g.id = s.groups_id
group by (g.id, extract(month from s.date_of_birth))
order by (g.num, extract(month from s.date_of_birth))

select 
	group_num,
	month,
	count(*)
from (
	select 	
		g.num as group_num,
		extract(month from s.date_of_birth) as month
	from student s 
	join groups g on g.id = s.groups_id
) group by (group_num, month)
order by (group_num, month)

select 
	min(date_of_birth),
	max(date_of_birth)
from student s
where groups_id=1

select distinct first_name from student order by first_name

select 
	distinct first_name,
	count(*)
from student
group by first_name
order by first_name

select * from student where EXTRACT(month from date_of_birth) = 1

select * from student s order by inn offset 2 limit 3

select * from student order by date_of_birth asc limit 1

select * from student order by date_of_birth desc limit 1


ar(64),
    date_of_birth date not null,
    inn int8 NOT NULL,
    CONSTRAINT teacher_pkey PRIMARY KEY (id),
	CONSTRAINT teacher_inn_uniq UNIQUE (inn)
);
insert into teacher (first_name, last_name, middle_name, date_of_birth, inn) values 
('Матвей', 'Петров', 'Петрович', '1970-01-01', 525617886911),
('Иван', 'Иванов', 'Матвеевич', '1966-02-02', 525671889912),
('Никита', 'Никитин', 'Иванович', '1967-03-03', 528677889913),
('Екатерина', 'Маринина', 'Ивановна', '1988-03-04', 525657819914),
('Ольга', 'Сергеева', 'Алексеевна', '1978-01-01', 125671889915);
CREATE TABLE teaching (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    subject_id int8 NOT NULL,
    teacher_id int8 NOT NULL,
    group_id int8 NOT NULL,
    CONSTRAINT teaching_pkey PRIMARY KEY (id)
);
insert into teaching(teacher_id, subject_id, group_id) values 
(1, 1, 1), (1, 1, 2), (2, 2, 1), (3, 2, 2), (2, 2, 3), (3, 2, 4),
(5, 3, 3), (5, 3, 4), (4, 4, 3), (4, 4, 4), (1, 4, 5), (2, 4, 6),
(4, 5, 1), (4, 5, 2), (5, 6, 5), (5, 6, 6);
CREATE TABLE bonus_coeff (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    sections varchar(64) NOT NULL,
    coeff int8 NOT NULL,
    CONSTRAINT bonus_coeff_pkey PRIMARY KEY (id)
);
insert into bonus_coeff(sections, coeff) values 
('Олимпиада по математике', 1000), ('Хор', 500), ('Олимпиада по информатике', 1500);
CREATE TABLE bonus (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    student_id int8 NOT NULL,
    sections_id int8 NOT NULL,
    CONSTRAINT bonus_pkey PRIMARY KEY (id)
);
insert into bonus(student_id, sections_id) values 
(3, 2), (5, 1), (33, 3), (6, 2), (7, 1), (32, 3), (9, 2), (12, 1), (19, 3);


